/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RejectedRouteImport } from './routes/rejected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as ArtifactsIdRouteImport } from './routes/artifacts.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedRoute = RejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIdRoute = ArtifactsIdRouteImport.update({
  id: '/artifacts/$id',
  path: '/artifacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rejected': typeof RejectedRoute
  '/verify': typeof VerifyRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rejected': typeof RejectedRoute
  '/verify': typeof VerifyRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/artifacts': typeof ArtifactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rejected': typeof RejectedRoute
  '/verify': typeof VerifyRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rejected' | '/verify' | '/artifacts/$id' | '/artifacts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rejected' | '/verify' | '/artifacts/$id' | '/artifacts'
  id:
    | '__root__'
    | '/'
    | '/rejected'
    | '/verify'
    | '/artifacts/$id'
    | '/artifacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RejectedRoute: typeof RejectedRoute
  VerifyRoute: typeof VerifyRoute
  ArtifactsIdRoute: typeof ArtifactsIdRoute
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected': {
      id: '/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof RejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$id': {
      id: '/artifacts/$id'
      path: '/artifacts/$id'
      fullPath: '/artifacts/$id'
      preLoaderRoute: typeof ArtifactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RejectedRoute: RejectedRoute,
  VerifyRoute: VerifyRoute,
  ArtifactsIdRoute: ArtifactsIdRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
